//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 10:46:39 AM CEST 
//


package models.rs.gov.parlament.propisi;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.gov.parlament.propisi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Stav_QNAME = new QName("http://www.parlament.gov.rs/propisi", "Stav");
    private final static QName _Alineja_QNAME = new QName("http://www.parlament.gov.rs/propisi", "Alineja");
    private final static QName _Podtacka_QNAME = new QName("http://www.parlament.gov.rs/propisi", "Podtacka");
    private final static QName _Tacka_QNAME = new QName("http://www.parlament.gov.rs/propisi", "Tacka");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.gov.parlament.propisi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Propis }
     * 
     */
    public Propis createPropis() {
        return new Propis();
    }

    /**
     * Create an instance of {@link Propis.Prilozi }
     * 
     */
    public Propis.Prilozi createPropisPrilozi() {
        return new Propis.Prilozi();
    }

    /**
     * Create an instance of {@link PodtackaTip }
     * 
     */
    public PodtackaTip createPodtackaTip() {
        return new PodtackaTip();
    }

    /**
     * Create an instance of {@link TackaTip }
     * 
     */
    public TackaTip createTackaTip() {
        return new TackaTip();
    }

    /**
     * Create an instance of {@link Preambula }
     * 
     */
    public Preambula createPreambula() {
        return new Preambula();
    }

    /**
     * Create an instance of {@link Odeljak }
     * 
     */
    public Odeljak createOdeljak() {
        return new Odeljak();
    }

    /**
     * Create an instance of {@link Pododeljak }
     * 
     */
    public Pododeljak createPododeljak() {
        return new Pododeljak();
    }

    /**
     * Create an instance of {@link Clan }
     * 
     */
    public Clan createClan() {
        return new Clan();
    }

    /**
     * Create an instance of {@link StavTip }
     * 
     */
    public StavTip createStavTip() {
        return new StavTip();
    }

    /**
     * Create an instance of {@link Referenca }
     * 
     */
    public Referenca createReferenca() {
        return new Referenca();
    }

    /**
     * Create an instance of {@link Deo }
     * 
     */
    public Deo createDeo() {
        return new Deo();
    }

    /**
     * Create an instance of {@link Glava }
     * 
     */
    public Glava createGlava() {
        return new Glava();
    }

    /**
     * Create an instance of {@link AlinejaTip }
     * 
     */
    public AlinejaTip createAlinejaTip() {
        return new AlinejaTip();
    }

    /**
     * Create an instance of {@link Propis.Sadrzaj }
     * 
     */
    public Propis.Sadrzaj createPropisSadrzaj() {
        return new Propis.Sadrzaj();
    }

    /**
     * Create an instance of {@link Propisi }
     * 
     */
    public Propisi createPropisi() {
        return new Propisi();
    }

    /**
     * Create an instance of {@link Propis.Prilozi.Prilog }
     * 
     */
    public Propis.Prilozi.Prilog createPropisPriloziPrilog() {
        return new Propis.Prilozi.Prilog();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StavTip }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.parlament.gov.rs/propisi", name = "Stav")
    public JAXBElement<StavTip> createStav(StavTip value) {
        return new JAXBElement<StavTip>(_Stav_QNAME, StavTip.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AlinejaTip }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.parlament.gov.rs/propisi", name = "Alineja")
    public JAXBElement<AlinejaTip> createAlineja(AlinejaTip value) {
        return new JAXBElement<AlinejaTip>(_Alineja_QNAME, AlinejaTip.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PodtackaTip }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.parlament.gov.rs/propisi", name = "Podtacka")
    public JAXBElement<PodtackaTip> createPodtacka(PodtackaTip value) {
        return new JAXBElement<PodtackaTip>(_Podtacka_QNAME, PodtackaTip.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TackaTip }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.parlament.gov.rs/propisi", name = "Tacka")
    public JAXBElement<TackaTip> createTacka(TackaTip value) {
        return new JAXBElement<TackaTip>(_Tacka_QNAME, TackaTip.class, null, value);
    }

}
