//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 04:28:13 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.parlament.gov.rs/propisi",
                                     elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
                                     xmlns = { @javax.xml.bind.annotation.XmlNs(prefix="pp", namespaceURI="http://www.parlament.gov.rs/propisi")})
package models.rs.gov.parlament.propisi;
