//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 10:46:39 AM CEST 
//


package models.rs.gov.parlament.propisi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pravni_osnov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Naziv_saglasnog_organa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.parlament.gov.rs/propisi}Status_akta"/>
 *         &lt;element name="Oblast" type="{http://www.parlament.gov.rs/propisi}Taksonomska_oblast"/>
 *         &lt;element name="Predlagac" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Datum_predaje" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Datum_glasanja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Datum_objave" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Datum_pocetka_vazenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Datum_prestanka_vazenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Broj_glasova_za" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Broj_glasova_protiv" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Broj_glasova_uzdrzano" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Objavljen_u_sluzbenom_glasniku" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pravniOsnov",
    "nazivOrgana",
    "nazivSaglasnogOrgana",
    "status",
    "oblast",
    "predlagac",
    "datumPredaje",
    "datumGlasanja",
    "datumObjave",
    "datumPocetkaVazenja",
    "datumPrestankaVazenja",
    "brojGlasovaZa",
    "brojGlasovaProtiv",
    "brojGlasovaUzdrzano",
    "objavljenUSluzbenomGlasniku"
})
@XmlRootElement(name = "Preambula")
public class Preambula {

    @XmlElement(name = "Pravni_osnov", required = true)
    protected String pravniOsnov;
    @XmlElement(name = "Naziv_organa", required = true)
    protected String nazivOrgana;
    @XmlElement(name = "Naziv_saglasnog_organa")
    protected String nazivSaglasnogOrgana;
    @XmlElement(name = "Status", required = true)
    protected StatusAkta status;
    @XmlElement(name = "Oblast", required = true)
    protected TaksonomskaOblast oblast;
    @XmlElement(name = "Predlagac", required = true)
    protected String predlagac;
    @XmlElement(name = "Datum_predaje", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPredaje;
    @XmlElement(name = "Datum_glasanja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumGlasanja;
    @XmlElement(name = "Datum_objave", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumObjave;
    @XmlElement(name = "Datum_pocetka_vazenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPocetkaVazenja;
    @XmlElement(name = "Datum_prestanka_vazenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPrestankaVazenja;
    @XmlElement(name = "Broj_glasova_za")
    protected int brojGlasovaZa;
    @XmlElement(name = "Broj_glasova_protiv")
    protected int brojGlasovaProtiv;
    @XmlElement(name = "Broj_glasova_uzdrzano")
    protected int brojGlasovaUzdrzano;
    @XmlElement(name = "Objavljen_u_sluzbenom_glasniku", required = true)
    protected String objavljenUSluzbenomGlasniku;

    /**
     * Gets the value of the pravniOsnov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPravniOsnov() {
        return pravniOsnov;
    }

    /**
     * Sets the value of the pravniOsnov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPravniOsnov(String value) {
        this.pravniOsnov = value;
    }

    /**
     * Gets the value of the nazivOrgana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivOrgana() {
        return nazivOrgana;
    }

    /**
     * Sets the value of the nazivOrgana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivOrgana(String value) {
        this.nazivOrgana = value;
    }

    /**
     * Gets the value of the nazivSaglasnogOrgana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivSaglasnogOrgana() {
        return nazivSaglasnogOrgana;
    }

    /**
     * Sets the value of the nazivSaglasnogOrgana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivSaglasnogOrgana(String value) {
        this.nazivSaglasnogOrgana = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusAkta }
     *     
     */
    public StatusAkta getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusAkta }
     *     
     */
    public void setStatus(StatusAkta value) {
        this.status = value;
    }

    /**
     * Gets the value of the oblast property.
     * 
     * @return
     *     possible object is
     *     {@link TaksonomskaOblast }
     *     
     */
    public TaksonomskaOblast getOblast() {
        return oblast;
    }

    /**
     * Sets the value of the oblast property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaksonomskaOblast }
     *     
     */
    public void setOblast(TaksonomskaOblast value) {
        this.oblast = value;
    }

    /**
     * Gets the value of the predlagac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredlagac() {
        return predlagac;
    }

    /**
     * Sets the value of the predlagac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredlagac(String value) {
        this.predlagac = value;
    }

    /**
     * Gets the value of the datumPredaje property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPredaje() {
        return datumPredaje;
    }

    /**
     * Sets the value of the datumPredaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPredaje(XMLGregorianCalendar value) {
        this.datumPredaje = value;
    }

    /**
     * Gets the value of the datumGlasanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumGlasanja() {
        return datumGlasanja;
    }

    /**
     * Sets the value of the datumGlasanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumGlasanja(XMLGregorianCalendar value) {
        this.datumGlasanja = value;
    }

    /**
     * Gets the value of the datumObjave property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumObjave() {
        return datumObjave;
    }

    /**
     * Sets the value of the datumObjave property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumObjave(XMLGregorianCalendar value) {
        this.datumObjave = value;
    }

    /**
     * Gets the value of the datumPocetkaVazenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPocetkaVazenja() {
        return datumPocetkaVazenja;
    }

    /**
     * Sets the value of the datumPocetkaVazenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPocetkaVazenja(XMLGregorianCalendar value) {
        this.datumPocetkaVazenja = value;
    }

    /**
     * Gets the value of the datumPrestankaVazenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPrestankaVazenja() {
        return datumPrestankaVazenja;
    }

    /**
     * Sets the value of the datumPrestankaVazenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPrestankaVazenja(XMLGregorianCalendar value) {
        this.datumPrestankaVazenja = value;
    }

    /**
     * Gets the value of the brojGlasovaZa property.
     * 
     */
    public int getBrojGlasovaZa() {
        return brojGlasovaZa;
    }

    /**
     * Sets the value of the brojGlasovaZa property.
     * 
     */
    public void setBrojGlasovaZa(int value) {
        this.brojGlasovaZa = value;
    }

    /**
     * Gets the value of the brojGlasovaProtiv property.
     * 
     */
    public int getBrojGlasovaProtiv() {
        return brojGlasovaProtiv;
    }

    /**
     * Sets the value of the brojGlasovaProtiv property.
     * 
     */
    public void setBrojGlasovaProtiv(int value) {
        this.brojGlasovaProtiv = value;
    }

    /**
     * Gets the value of the brojGlasovaUzdrzano property.
     * 
     */
    public int getBrojGlasovaUzdrzano() {
        return brojGlasovaUzdrzano;
    }

    /**
     * Sets the value of the brojGlasovaUzdrzano property.
     * 
     */
    public void setBrojGlasovaUzdrzano(int value) {
        this.brojGlasovaUzdrzano = value;
    }

    /**
     * Gets the value of the objavljenUSluzbenomGlasniku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjavljenUSluzbenomGlasniku() {
        return objavljenUSluzbenomGlasniku;
    }

    /**
     * Sets the value of the objavljenUSluzbenomGlasniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjavljenUSluzbenomGlasniku(String value) {
        this.objavljenUSluzbenomGlasniku = value;
    }

}
