//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.01 at 11:17:58 AM CEST 
//


package models.rs.gov.parlament.propisi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pravni_osnov">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Materijalni" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Formalni" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Naziv_saglasnog_organa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pravniOsnov",
    "nazivOrgana",
    "nazivSaglasnogOrgana"
})
@XmlRootElement(name = "Preambula")
public class Preambula {

    @XmlElement(name = "Pravni_osnov", required = true)
    protected PravniOsnov pravniOsnov;
    @XmlElement(name = "Naziv_organa", required = true)
    protected String nazivOrgana;
    @XmlElement(name = "Naziv_saglasnog_organa")
    protected String nazivSaglasnogOrgana;

    /**
     * Gets the value of the pravniOsnov property.
     * 
     * @return
     *     possible object is
     *     {@link PravniOsnov }
     *     
     */
    public PravniOsnov getPravniOsnov() {
        return pravniOsnov;
    }

    /**
     * Sets the value of the pravniOsnov property.
     * 
     * @param value
     *     allowed object is
     *     {@link PravniOsnov }
     *     
     */
    public void setPravniOsnov(PravniOsnov value) {
        this.pravniOsnov = value;
    }

    /**
     * Gets the value of the nazivOrgana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivOrgana() {
        return nazivOrgana;
    }

    /**
     * Sets the value of the nazivOrgana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivOrgana(String value) {
        this.nazivOrgana = value;
    }

    /**
     * Gets the value of the nazivSaglasnogOrgana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivSaglasnogOrgana() {
        return nazivSaglasnogOrgana;
    }

    /**
     * Sets the value of the nazivSaglasnogOrgana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivSaglasnogOrgana(String value) {
        this.nazivSaglasnogOrgana = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Materijalni" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Formalni" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "materijalni",
        "formalni"
    })
    public static class PravniOsnov {

        @XmlElement(name = "Materijalni", required = true)
        protected String materijalni;
        @XmlElement(name = "Formalni", required = true)
        protected String formalni;

        /**
         * Gets the value of the materijalni property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaterijalni() {
            return materijalni;
        }

        /**
         * Sets the value of the materijalni property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaterijalni(String value) {
            this.materijalni = value;
        }

        /**
         * Gets the value of the formalni property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormalni() {
            return formalni;
        }

        /**
         * Sets the value of the formalni property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormalni(String value) {
            this.formalni = value;
        }

    }

}
