//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 10:46:39 AM CEST 
//


package models.rs.gov.parlament.propisi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.parlament.gov.rs/propisi}Preambula" minOccurs="0"/>
 *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sadrzaj">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.parlament.gov.rs/propisi}Deo" maxOccurs="unbounded"/>
 *                   &lt;element ref="{http://www.parlament.gov.rs/propisi}Glava" maxOccurs="unbounded"/>
 *                   &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="20"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Prilozi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Prilog" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Oznaka_priloga" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Uri_propisa" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Tip_dokumenta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="PROPIS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "preambula",
    "naziv",
    "sadrzaj",
    "prilozi"
})
@XmlRootElement(name = "Propis")
public class Propis {

    @XmlElement(name = "Preambula")
    protected Preambula preambula;
    @XmlElement(name = "Naziv", required = true)
    protected String naziv;
    @XmlElement(name = "Sadrzaj", required = true)
    protected Propis.Sadrzaj sadrzaj;
    @XmlElement(name = "Prilozi", required = true)
    protected Propis.Prilozi prilozi;
    @XmlAttribute(name = "Uri_propisa", required = true)
    protected String uriPropisa;
    @XmlAttribute(name = "Tip_dokumenta", required = true)
    protected String tipDokumenta;

    /**
     * Gets the value of the preambula property.
     * 
     * @return
     *     possible object is
     *     {@link Preambula }
     *     
     */
    public Preambula getPreambula() {
        return preambula;
    }

    /**
     * Sets the value of the preambula property.
     * 
     * @param value
     *     allowed object is
     *     {@link Preambula }
     *     
     */
    public void setPreambula(Preambula value) {
        this.preambula = value;
    }

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the sadrzaj property.
     * 
     * @return
     *     possible object is
     *     {@link Propis.Sadrzaj }
     *     
     */
    public Propis.Sadrzaj getSadrzaj() {
        return sadrzaj;
    }

    /**
     * Sets the value of the sadrzaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Propis.Sadrzaj }
     *     
     */
    public void setSadrzaj(Propis.Sadrzaj value) {
        this.sadrzaj = value;
    }

    /**
     * Gets the value of the prilozi property.
     * 
     * @return
     *     possible object is
     *     {@link Propis.Prilozi }
     *     
     */
    public Propis.Prilozi getPrilozi() {
        return prilozi;
    }

    /**
     * Sets the value of the prilozi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Propis.Prilozi }
     *     
     */
    public void setPrilozi(Propis.Prilozi value) {
        this.prilozi = value;
    }

    /**
     * Gets the value of the uriPropisa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUriPropisa() {
        return uriPropisa;
    }

    /**
     * Sets the value of the uriPropisa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUriPropisa(String value) {
        this.uriPropisa = value;
    }

    /**
     * Gets the value of the tipDokumenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipDokumenta() {
        if (tipDokumenta == null) {
            return "PROPIS";
        } else {
            return tipDokumenta;
        }
    }

    /**
     * Sets the value of the tipDokumenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipDokumenta(String value) {
        this.tipDokumenta = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Prilog" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="Oznaka_priloga" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prilog"
    })
    public static class Prilozi {

        @XmlElement(name = "Prilog")
        protected List<Propis.Prilozi.Prilog> prilog;

        /**
         * Gets the value of the prilog property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the prilog property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPrilog().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Propis.Prilozi.Prilog }
         * 
         * 
         */
        public List<Propis.Prilozi.Prilog> getPrilog() {
            if (prilog == null) {
                prilog = new ArrayList<Propis.Prilozi.Prilog>();
            }
            return this.prilog;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="Oznaka_priloga" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Prilog {

            @XmlAttribute(name = "Oznaka_priloga")
            protected Integer oznakaPriloga;

            /**
             * Gets the value of the oznakaPriloga property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getOznakaPriloga() {
                return oznakaPriloga;
            }

            /**
             * Sets the value of the oznakaPriloga property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setOznakaPriloga(Integer value) {
                this.oznakaPriloga = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.parlament.gov.rs/propisi}Deo" maxOccurs="unbounded"/>
     *         &lt;element ref="{http://www.parlament.gov.rs/propisi}Glava" maxOccurs="unbounded"/>
     *         &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="20"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deo",
        "glava",
        "clan"
    })
    public static class Sadrzaj {

        @XmlElement(name = "Deo")
        protected List<Deo> deo;
        @XmlElement(name = "Glava")
        protected List<Glava> glava;
        @XmlElement(name = "Clan")
        protected List<Clan> clan;

        /**
         * Gets the value of the deo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the deo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDeo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Deo }
         * 
         * 
         */
        public List<Deo> getDeo() {
            if (deo == null) {
                deo = new ArrayList<Deo>();
            }
            return this.deo;
        }

        /**
         * Gets the value of the glava property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the glava property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGlava().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Glava }
         * 
         * 
         */
        public List<Glava> getGlava() {
            if (glava == null) {
                glava = new ArrayList<Glava>();
            }
            return this.glava;
        }

        /**
         * Gets the value of the clan property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the clan property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClan().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Clan }
         * 
         * 
         */
        public List<Clan> getClan() {
            if (clan == null) {
                clan = new ArrayList<Clan>();
            }
            return this.clan;
        }

    }

}
