//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.12 at 06:58:41 PM CEST 
//


package models.rs.gov.parlament.propisi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="Oznaka_propisa" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Oznaka_clana" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "Referenca")
public class Referenca {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "Oznaka_propisa", required = true)
    protected int oznakaPropisa;
    @XmlAttribute(name = "Oznaka_clana", required = true)
    protected int oznakaClana;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the oznakaPropisa property.
     * 
     */
    public int getOznakaPropisa() {
        return oznakaPropisa;
    }

    /**
     * Sets the value of the oznakaPropisa property.
     * 
     */
    public void setOznakaPropisa(int value) {
        this.oznakaPropisa = value;
    }

    /**
     * Gets the value of the oznakaClana property.
     * 
     */
    public int getOznakaClana() {
        return oznakaClana;
    }

    /**
     * Sets the value of the oznakaClana property.
     * 
     */
    public void setOznakaClana(int value) {
        this.oznakaClana = value;
    }

}
