//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 10:46:39 AM CEST 
//


package models.rs.gov.parlament.propisi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Taksonomska_oblast.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Taksonomska_oblast">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ZDRAVSTVO"/>
 *     &lt;enumeration value="PROSVETA"/>
 *     &lt;enumeration value="SPORT"/>
 *     &lt;enumeration value="SAOBRACAJ"/>
 *     &lt;enumeration value="TURIZAM"/>
 *     &lt;enumeration value="PRAVO"/>
 *     &lt;enumeration value="EKONOMIJA"/>
 *     &lt;enumeration value="KULTURA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Taksonomska_oblast")
@XmlEnum
public enum TaksonomskaOblast {

    ZDRAVSTVO,
    PROSVETA,
    SPORT,
    SAOBRACAJ,
    TURIZAM,
    PRAVO,
    EKONOMIJA,
    KULTURA;

    public String value() {
        return name();
    }

    public static TaksonomskaOblast fromValue(String v) {
        return valueOf(v);
    }

}
