//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 02:13:45 PM CEST
//


package models.rs.gov.parlament.amandmani;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.parlament.gov.rs/amandmani}Preambula"/>
 *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Deo_za_izmenu">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Uri_propisa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Oznaka_dela" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Oznaka_glave" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Oznaka_clana" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Oznaka_stava" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Oznaka_tacke" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Oznaka_podtacke" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Oznaka_alineje" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Sadrzaj" type="{http://www.parlament.gov.rs/amandmani}Sadrzaj_tip"/>
 *         &lt;element name="Obrazlozenje" type="{http://www.parlament.gov.rs/amandmani}Sadrzaj_tip"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Uri_amandmana" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Tip_dokumenta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="AMANDMAN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "preambula",
        "naziv",
        "deoZaIzmenu",
        "sadrzaj",
        "obrazlozenje"
})
@XmlRootElement(name = "Amandman")
public class Amandman {

    @XmlElement(name = "Preambula", required = true)
    protected Preambula preambula;
    @XmlElement(name = "Naziv", required = true)
    protected String naziv;
    @XmlElement(name = "Deo_za_izmenu", required = true)
    protected Amandman.DeoZaIzmenu deoZaIzmenu;
    @XmlElement(name = "Sadrzaj", required = true)
    protected SadrzajTip sadrzaj;
    @XmlElement(name = "Obrazlozenje", required = true)
    protected SadrzajTip obrazlozenje;
    @XmlAttribute(name = "Uri_amandmana", required = true)
    protected String uriAmandmana;
    @XmlAttribute(name = "Tip_dokumenta", required = true)
    protected String tipDokumenta;

    /**
     * Gets the value of the preambula property.
     *
     * @return
     *     possible object is
     *     {@link Preambula }
     *
     */
    public Preambula getPreambula() {
        return preambula;
    }

    /**
     * Sets the value of the preambula property.
     *
     * @param value
     *     allowed object is
     *     {@link Preambula }
     *
     */
    public void setPreambula(Preambula value) {
        this.preambula = value;
    }

    /**
     * Gets the value of the naziv property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the deoZaIzmenu property.
     *
     * @return
     *     possible object is
     *     {@link Amandman.DeoZaIzmenu }
     *
     */
    public Amandman.DeoZaIzmenu getDeoZaIzmenu() {
        return deoZaIzmenu;
    }

    /**
     * Sets the value of the deoZaIzmenu property.
     *
     * @param value
     *     allowed object is
     *     {@link Amandman.DeoZaIzmenu }
     *
     */
    public void setDeoZaIzmenu(Amandman.DeoZaIzmenu value) {
        this.deoZaIzmenu = value;
    }

    /**
     * Gets the value of the sadrzaj property.
     *
     * @return
     *     possible object is
     *     {@link SadrzajTip }
     *
     */
    public SadrzajTip getSadrzaj() {
        return sadrzaj;
    }

    /**
     * Sets the value of the sadrzaj property.
     *
     * @param value
     *     allowed object is
     *     {@link SadrzajTip }
     *
     */
    public void setSadrzaj(SadrzajTip value) {
        this.sadrzaj = value;
    }

    /**
     * Gets the value of the obrazlozenje property.
     *
     * @return
     *     possible object is
     *     {@link SadrzajTip }
     *
     */
    public SadrzajTip getObrazlozenje() {
        return obrazlozenje;
    }

    /**
     * Sets the value of the obrazlozenje property.
     *
     * @param value
     *     allowed object is
     *     {@link SadrzajTip }
     *
     */
    public void setObrazlozenje(SadrzajTip value) {
        this.obrazlozenje = value;
    }

    /**
     * Gets the value of the uriAmandmana property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUriAmandmana() {
        return uriAmandmana;
    }

    /**
     * Sets the value of the uriAmandmana property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUriAmandmana(String value) {
        this.uriAmandmana = value;
    }

    /**
     * Gets the value of the tipDokumenta property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTipDokumenta() {
        if (tipDokumenta == null) {
            return "AMANDMAN";
        } else {
            return tipDokumenta;
        }
    }

    /**
     * Sets the value of the tipDokumenta property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTipDokumenta(String value) {
        this.tipDokumenta = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Uri_propisa" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Oznaka_dela" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Oznaka_glave" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Oznaka_clana" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Oznaka_stava" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Oznaka_tacke" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Oznaka_podtacke" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Oznaka_alineje" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "uriPropisa",
            "oznakaDela",
            "oznakaGlave",
            "oznakaClana",
            "oznakaStava",
            "oznakaTacke",
            "oznakaPodtacke",
            "oznakaAlineje"
    })
    public static class DeoZaIzmenu {

        @XmlElement(name = "Uri_propisa", required = true)
        protected String uriPropisa;
        @XmlElement(name = "Oznaka_dela")
        protected Integer oznakaDela;
        @XmlElement(name = "Oznaka_glave")
        protected Integer oznakaGlave;
        @XmlElement(name = "Oznaka_clana")
        protected int oznakaClana;
        @XmlElement(name = "Oznaka_stava")
        protected Integer oznakaStava;
        @XmlElement(name = "Oznaka_tacke")
        protected Integer oznakaTacke;
        @XmlElement(name = "Oznaka_podtacke")
        protected Integer oznakaPodtacke;
        @XmlElement(name = "Oznaka_alineje")
        protected Integer oznakaAlineje;

        /**
         * Gets the value of the uriPropisa property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getUriPropisa() {
            return uriPropisa;
        }

        /**
         * Sets the value of the uriPropisa property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setUriPropisa(String value) {
            this.uriPropisa = value;
        }

        /**
         * Gets the value of the oznakaDela property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getOznakaDela() {
            return oznakaDela;
        }

        /**
         * Sets the value of the oznakaDela property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setOznakaDela(Integer value) {
            this.oznakaDela = value;
        }

        /**
         * Gets the value of the oznakaGlave property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getOznakaGlave() {
            return oznakaGlave;
        }

        /**
         * Sets the value of the oznakaGlave property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setOznakaGlave(Integer value) {
            this.oznakaGlave = value;
        }

        /**
         * Gets the value of the oznakaClana property.
         *
         */
        public int getOznakaClana() {
            return oznakaClana;
        }

        /**
         * Sets the value of the oznakaClana property.
         *
         */
        public void setOznakaClana(int value) {
            this.oznakaClana = value;
        }

        /**
         * Gets the value of the oznakaStava property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getOznakaStava() {
            return oznakaStava;
        }

        /**
         * Sets the value of the oznakaStava property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setOznakaStava(Integer value) {
            this.oznakaStava = value;
        }

        /**
         * Gets the value of the oznakaTacke property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getOznakaTacke() {
            return oznakaTacke;
        }

        /**
         * Sets the value of the oznakaTacke property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setOznakaTacke(Integer value) {
            this.oznakaTacke = value;
        }

        /**
         * Gets the value of the oznakaPodtacke property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getOznakaPodtacke() {
            return oznakaPodtacke;
        }

        /**
         * Sets the value of the oznakaPodtacke property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setOznakaPodtacke(Integer value) {
            this.oznakaPodtacke = value;
        }

        /**
         * Gets the value of the oznakaAlineje property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getOznakaAlineje() {
            return oznakaAlineje;
        }

        /**
         * Sets the value of the oznakaAlineje property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setOznakaAlineje(Integer value) {
            this.oznakaAlineje = value;
        }

    }

}
