//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.03 at 04:28:13 PM CEST 
//


package models.rs.gov.parlament.amandmani;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import models.rs.gov.parlament.korisnici.OdbornikTip;
import models.rs.gov.parlament.korisnici.PredsednikSkupstineTip;
import models.rs.gov.parlament.propisi.Clan;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Amandman" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Naziv_predloga" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Tekst_za_izmenu">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="Izmena">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Dopuna">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Brisanje">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Obrazlozenje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Saglasni">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element ref="{http://www.parlament.gov.rs/korisnici}Odbornik"/>
 *                             &lt;element ref="{http://www.parlament.gov.rs/korisnici}Predsednik_skupstine"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Po_clanu_poslovnika_narodne_skupstine" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "amandman"
})
@XmlRootElement(name = "Amandmani")
public class Amandmani {

    @XmlElement(name = "Amandman", required = true)
    protected List<Amandmani.Amandman> amandman;

    /**
     * Gets the value of the amandman property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the amandman property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAmandman().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Amandmani.Amandman }
     * 
     * 
     */
    public List<Amandmani.Amandman> getAmandman() {
        if (amandman == null) {
            amandman = new ArrayList<Amandmani.Amandman>();
        }
        return this.amandman;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Naziv_predloga" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Tekst_za_izmenu">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="Izmena">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Dopuna">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Brisanje">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Obrazlozenje" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Saglasni">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element ref="{http://www.parlament.gov.rs/korisnici}Odbornik"/>
     *                   &lt;element ref="{http://www.parlament.gov.rs/korisnici}Predsednik_skupstine"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Po_clanu_poslovnika_narodne_skupstine" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nazivPredloga",
        "tekstZaIzmenu",
        "obrazlozenje",
        "saglasni"
    })
    public static class Amandman {

        @XmlElement(name = "Naziv_predloga", required = true)
        protected String nazivPredloga;
        @XmlElement(name = "Tekst_za_izmenu", required = true)
        protected Amandmani.Amandman.TekstZaIzmenu tekstZaIzmenu;
        @XmlElement(name = "Obrazlozenje", required = true)
        protected String obrazlozenje;
        @XmlElement(name = "Saglasni", required = true)
        protected Amandmani.Amandman.Saglasni saglasni;
        @XmlAttribute(name = "Po_clanu_poslovnika_narodne_skupstine")
        protected Integer poClanuPoslovnikaNarodneSkupstine;

        /**
         * Gets the value of the nazivPredloga property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivPredloga() {
            return nazivPredloga;
        }

        /**
         * Sets the value of the nazivPredloga property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivPredloga(String value) {
            this.nazivPredloga = value;
        }

        /**
         * Gets the value of the tekstZaIzmenu property.
         * 
         * @return
         *     possible object is
         *     {@link Amandmani.Amandman.TekstZaIzmenu }
         *     
         */
        public Amandmani.Amandman.TekstZaIzmenu getTekstZaIzmenu() {
            return tekstZaIzmenu;
        }

        /**
         * Sets the value of the tekstZaIzmenu property.
         * 
         * @param value
         *     allowed object is
         *     {@link Amandmani.Amandman.TekstZaIzmenu }
         *     
         */
        public void setTekstZaIzmenu(Amandmani.Amandman.TekstZaIzmenu value) {
            this.tekstZaIzmenu = value;
        }

        /**
         * Gets the value of the obrazlozenje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObrazlozenje() {
            return obrazlozenje;
        }

        /**
         * Sets the value of the obrazlozenje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObrazlozenje(String value) {
            this.obrazlozenje = value;
        }

        /**
         * Gets the value of the saglasni property.
         * 
         * @return
         *     possible object is
         *     {@link Amandmani.Amandman.Saglasni }
         *     
         */
        public Amandmani.Amandman.Saglasni getSaglasni() {
            return saglasni;
        }

        /**
         * Sets the value of the saglasni property.
         * 
         * @param value
         *     allowed object is
         *     {@link Amandmani.Amandman.Saglasni }
         *     
         */
        public void setSaglasni(Amandmani.Amandman.Saglasni value) {
            this.saglasni = value;
        }

        /**
         * Gets the value of the poClanuPoslovnikaNarodneSkupstine property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPoClanuPoslovnikaNarodneSkupstine() {
            return poClanuPoslovnikaNarodneSkupstine;
        }

        /**
         * Sets the value of the poClanuPoslovnikaNarodneSkupstine property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPoClanuPoslovnikaNarodneSkupstine(Integer value) {
            this.poClanuPoslovnikaNarodneSkupstine = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element ref="{http://www.parlament.gov.rs/korisnici}Odbornik"/>
         *         &lt;element ref="{http://www.parlament.gov.rs/korisnici}Predsednik_skupstine"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Saglasni {

            @XmlElement(name = "Odbornik", namespace = "http://www.parlament.gov.rs/korisnici", required = true)
            protected OdbornikTip odbornik;
            @XmlElement(name = "Predsednik_skupstine", namespace = "http://www.parlament.gov.rs/korisnici", required = true)
            protected PredsednikSkupstineTip predsednikSkupstine;

            /**
             * Gets the value of the odbornik property.
             * 
             * @return
             *     possible object is
             *     {@link OdbornikTip }
             *     
             */
            public OdbornikTip getOdbornik() {
                return odbornik;
            }

            /**
             * Sets the value of the odbornik property.
             * 
             * @param value
             *     allowed object is
             *     {@link OdbornikTip }
             *     
             */
            public void setOdbornik(OdbornikTip value) {
                this.odbornik = value;
            }

            /**
             * Gets the value of the predsednikSkupstine property.
             * 
             * @return
             *     possible object is
             *     {@link PredsednikSkupstineTip }
             *     
             */
            public PredsednikSkupstineTip getPredsednikSkupstine() {
                return predsednikSkupstine;
            }

            /**
             * Sets the value of the predsednikSkupstine property.
             * 
             * @param value
             *     allowed object is
             *     {@link PredsednikSkupstineTip }
             *     
             */
            public void setPredsednikSkupstine(PredsednikSkupstineTip value) {
                this.predsednikSkupstine = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="Izmena">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Dopuna">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Brisanje">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "izmena",
            "dopuna",
            "brisanje"
        })
        public static class TekstZaIzmenu {

            @XmlElement(name = "Izmena")
            protected Amandmani.Amandman.TekstZaIzmenu.Izmena izmena;
            @XmlElement(name = "Dopuna")
            protected Amandmani.Amandman.TekstZaIzmenu.Dopuna dopuna;
            @XmlElement(name = "Brisanje")
            protected Amandmani.Amandman.TekstZaIzmenu.Brisanje brisanje;

            /**
             * Gets the value of the izmena property.
             * 
             * @return
             *     possible object is
             *     {@link Amandmani.Amandman.TekstZaIzmenu.Izmena }
             *     
             */
            public Amandmani.Amandman.TekstZaIzmenu.Izmena getIzmena() {
                return izmena;
            }

            /**
             * Sets the value of the izmena property.
             * 
             * @param value
             *     allowed object is
             *     {@link Amandmani.Amandman.TekstZaIzmenu.Izmena }
             *     
             */
            public void setIzmena(Amandmani.Amandman.TekstZaIzmenu.Izmena value) {
                this.izmena = value;
            }

            /**
             * Gets the value of the dopuna property.
             * 
             * @return
             *     possible object is
             *     {@link Amandmani.Amandman.TekstZaIzmenu.Dopuna }
             *     
             */
            public Amandmani.Amandman.TekstZaIzmenu.Dopuna getDopuna() {
                return dopuna;
            }

            /**
             * Sets the value of the dopuna property.
             * 
             * @param value
             *     allowed object is
             *     {@link Amandmani.Amandman.TekstZaIzmenu.Dopuna }
             *     
             */
            public void setDopuna(Amandmani.Amandman.TekstZaIzmenu.Dopuna value) {
                this.dopuna = value;
            }

            /**
             * Gets the value of the brisanje property.
             * 
             * @return
             *     possible object is
             *     {@link Amandmani.Amandman.TekstZaIzmenu.Brisanje }
             *     
             */
            public Amandmani.Amandman.TekstZaIzmenu.Brisanje getBrisanje() {
                return brisanje;
            }

            /**
             * Sets the value of the brisanje property.
             * 
             * @param value
             *     allowed object is
             *     {@link Amandmani.Amandman.TekstZaIzmenu.Brisanje }
             *     
             */
            public void setBrisanje(Amandmani.Amandman.TekstZaIzmenu.Brisanje value) {
                this.brisanje = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "clan"
            })
            public static class Brisanje {

                @XmlElement(name = "Clan", namespace = "http://www.parlament.gov.rs/propisi", required = true)
                protected List<Clan> clan;

                /**
                 * Gets the value of the clan property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the clan property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getClan().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Clan }
                 * 
                 * 
                 */
                public List<Clan> getClan() {
                    if (clan == null) {
                        clan = new ArrayList<Clan>();
                    }
                    return this.clan;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "clan"
            })
            public static class Dopuna {

                @XmlElement(name = "Clan", namespace = "http://www.parlament.gov.rs/propisi", required = true)
                protected List<Clan> clan;

                /**
                 * Gets the value of the clan property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the clan property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getClan().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Clan }
                 * 
                 * 
                 */
                public List<Clan> getClan() {
                    if (clan == null) {
                        clan = new ArrayList<Clan>();
                    }
                    return this.clan;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{http://www.parlament.gov.rs/propisi}Clan" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "clan"
            })
            public static class Izmena {

                @XmlElement(name = "Clan", namespace = "http://www.parlament.gov.rs/propisi", required = true)
                protected List<Clan> clan;

                /**
                 * Gets the value of the clan property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the clan property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getClan().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Clan }
                 * 
                 * 
                 */
                public List<Clan> getClan() {
                    if (clan == null) {
                        clan = new ArrayList<Clan>();
                    }
                    return this.clan;
                }

            }

        }

    }

}
