//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.12 at 06:58:41 PM CEST 
//


package models.rs.gov.parlament.amandmani;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import models.rs.gov.parlament.propisi.TaksonomskaOblast;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tip" type="{http://www.parlament.gov.rs/amandmani}Tip_amandmana"/>
 *         &lt;element name="Status" type="{http://www.parlament.gov.rs/amandmani}Status_amandmana"/>
 *         &lt;element name="Oblast" type="{http://www.parlament.gov.rs/propisi}Taksonomska_oblast"/>
 *         &lt;element name="Predlagac" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Datum_predaje" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Datum_glasanja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Broj_glasova_za" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Broj_glasova_protiv" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Broj_glasova_uzdrzano" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tip",
    "status",
    "oblast",
    "predlagac",
    "datumPredaje",
    "datumGlasanja",
    "brojGlasovaZa",
    "brojGlasovaProtiv",
    "brojGlasovaUzdrzano"
})
@XmlRootElement(name = "Preambula")
public class Preambula {

    @XmlElement(name = "Tip", required = true)
    protected TipAmandmana tip;
    @XmlElement(name = "Status", required = true)
    protected StatusAmandmana status;
    @XmlElement(name = "Oblast", required = true)
    protected TaksonomskaOblast oblast;
    @XmlElement(name = "Predlagac", required = true)
    protected String predlagac;
    @XmlElement(name = "Datum_predaje", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPredaje;
    @XmlElement(name = "Datum_glasanja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumGlasanja;
    @XmlElement(name = "Broj_glasova_za")
    protected int brojGlasovaZa;
    @XmlElement(name = "Broj_glasova_protiv")
    protected int brojGlasovaProtiv;
    @XmlElement(name = "Broj_glasova_uzdrzano")
    protected int brojGlasovaUzdrzano;

    /**
     * Gets the value of the tip property.
     * 
     * @return
     *     possible object is
     *     {@link TipAmandmana }
     *     
     */
    public TipAmandmana getTip() {
        return tip;
    }

    /**
     * Sets the value of the tip property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipAmandmana }
     *     
     */
    public void setTip(TipAmandmana value) {
        this.tip = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusAmandmana }
     *     
     */
    public StatusAmandmana getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusAmandmana }
     *     
     */
    public void setStatus(StatusAmandmana value) {
        this.status = value;
    }

    /**
     * Gets the value of the oblast property.
     * 
     * @return
     *     possible object is
     *     {@link TaksonomskaOblast }
     *     
     */
    public TaksonomskaOblast getOblast() {
        return oblast;
    }

    /**
     * Sets the value of the oblast property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaksonomskaOblast }
     *     
     */
    public void setOblast(TaksonomskaOblast value) {
        this.oblast = value;
    }

    /**
     * Gets the value of the predlagac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredlagac() {
        return predlagac;
    }

    /**
     * Sets the value of the predlagac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredlagac(String value) {
        this.predlagac = value;
    }

    /**
     * Gets the value of the datumPredaje property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPredaje() {
        return datumPredaje;
    }

    /**
     * Sets the value of the datumPredaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPredaje(XMLGregorianCalendar value) {
        this.datumPredaje = value;
    }

    /**
     * Gets the value of the datumGlasanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumGlasanja() {
        return datumGlasanja;
    }

    /**
     * Sets the value of the datumGlasanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumGlasanja(XMLGregorianCalendar value) {
        this.datumGlasanja = value;
    }

    /**
     * Gets the value of the brojGlasovaZa property.
     * 
     */
    public int getBrojGlasovaZa() {
        return brojGlasovaZa;
    }

    /**
     * Sets the value of the brojGlasovaZa property.
     * 
     */
    public void setBrojGlasovaZa(int value) {
        this.brojGlasovaZa = value;
    }

    /**
     * Gets the value of the brojGlasovaProtiv property.
     * 
     */
    public int getBrojGlasovaProtiv() {
        return brojGlasovaProtiv;
    }

    /**
     * Sets the value of the brojGlasovaProtiv property.
     * 
     */
    public void setBrojGlasovaProtiv(int value) {
        this.brojGlasovaProtiv = value;
    }

    /**
     * Gets the value of the brojGlasovaUzdrzano property.
     * 
     */
    public int getBrojGlasovaUzdrzano() {
        return brojGlasovaUzdrzano;
    }

    /**
     * Sets the value of the brojGlasovaUzdrzano property.
     * 
     */
    public void setBrojGlasovaUzdrzano(int value) {
        this.brojGlasovaUzdrzano = value;
    }

}
