//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.12 at 06:58:42 PM CEST 
//


package models.rs.gov.parlament.korisnici;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tip_korisnika.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Tip_korisnika">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GRADJANIN"/>
 *     &lt;enumeration value="ODBORNIK"/>
 *     &lt;enumeration value="PREDSEDNIK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Tip_korisnika")
@XmlEnum
public enum TipKorisnika {

    GRADJANIN,
    ODBORNIK,
    PREDSEDNIK;

    public String value() {
        return name();
    }

    public static TipKorisnika fromValue(String v) {
        return valueOf(v);
    }

}
